#!/usr/bin/env node
/* browser-icons.mjs — owner tool for the ASK browser-icon package.
 *
 *   node tools/browser-icons.mjs           regenerate favicon.ico
 *   node tools/browser-icons.mjs --check   verify every package invariant, exit non-zero on failure
 *
 * The package is ADOPTED, not designed here: favicon.svg, favicon-32.png and
 * apple-touch-icon.png carry the ratified expression, and their glyph geometry comes from
 * assets/logo-ASK.svg without redraw. Only favicon.ico is generated, and it is generated by
 * WRAPPING the exact bytes of favicon-32.png in an ICO container — PNG-in-ICO — so it introduces
 * no resampling and no pixel that is not already in a ratified asset. That is also what makes it
 * byte-deterministic: the payload is a copy, not a render.
 *
 * WHY THE THREE SOURCE ASSETS ARE PINNED BY FULL SHA-256, and not merely described.
 * Semantic checks alone cannot establish the ratified COMPOSITION. A verifier that only asserts
 * "viewBox present · lavender hex occurs once · three glyph paths equal logo-ASK.svg · PNG is
 * 32x32" will pass an icon whose wordmark has been scaled to 11%, translated off the canvas or
 * hidden at opacity 0, whose lavender rect no longer covers the square, or whose rasters have been
 * replaced wholesale at the same dimensions. All six were reproduced against an earlier revision of
 * this file. Because consumers are told to vendor EXACT owner bytes, the honest owner guard is the
 * exact byte identity; the semantic checks are retained on top of it, so a pin updated to the wrong
 * artwork still fails.
 *
 * An intentional visual revision updates the asset bytes AND these constants in the SAME reviewed
 * owner PR. That is the point: the change becomes visible in review instead of passing silently.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const P = (f) => path.join(ROOT, f);
const sha = (b) => crypto.createHash('sha256').update(b).digest('hex');

/* Full identities of the three RATIFIED source assets, adopted byte-identical from
   apexSolarKiss/ASK (origin/main 0f11ede) where this expression has been live. */
const RATIFIED = {
  'favicon.svg':          '1033f1c23123d78b8650de49ea413c85e1937014c866812229552c89d645cc6b',
  'favicon-32.png':       '9f08639c0523fae1aa7a782567b66d3ca5a9ac0929150a72deca9455f397d390',
  'apple-touch-icon.png': 'e2fc718650c99c9e610ad232a30dcf9308dcd5223094e06f04eeb502f2313b5d',
};

const FIELD = '#d4c6e1';      /* lavender-ASK, baked */
const INK   = '#ffffff';      /* wordmark pairing */
const VIEWBOX = '0 0 512 512';

/* ---------- PNG header reader ---------- */
function png(buf) {
  if (buf.readUInt32BE(0) !== 0x89504e47) throw new Error('not a PNG');
  if (buf.toString('ascii', 12, 16) !== 'IHDR') throw new Error('no IHDR');
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20), bitDepth: buf[24], colorType: buf[25] };
}

/* ---------- ICO container around an existing PNG ---------- */
function buildIco(pngBuf) {
  const { w, h } = png(pngBuf);
  const dim = (n) => (n >= 256 ? 0 : n);              /* 0 means 256 in the ICO spec */
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);                          /* reserved */
  header.writeUInt16LE(1, 2);                          /* type 1 = icon */
  header.writeUInt16LE(1, 4);                          /* one image */
  const entry = Buffer.alloc(16);
  entry[0] = dim(w); entry[1] = dim(h);
  entry[2] = 0;                                        /* palette colors */
  entry[3] = 0;                                        /* reserved */
  entry.writeUInt16LE(1, 4);                           /* color planes */
  entry.writeUInt16LE(32, 6);                          /* bits per pixel */
  entry.writeUInt32LE(pngBuf.length, 8);
  entry.writeUInt32LE(6 + 16, 12);                     /* offset */
  return Buffer.concat([header, entry, pngBuf]);
}

function parseIco(buf) {
  if (buf.readUInt16LE(0) !== 0 || buf.readUInt16LE(2) !== 1) throw new Error('bad ICO header');
  const count = buf.readUInt16LE(4);
  const out = [];
  for (let i = 0; i < count; i++) {
    const o = 6 + i * 16;
    const size = buf.readUInt32LE(o + 8), off = buf.readUInt32LE(o + 12);
    const payload = buf.subarray(off, off + size);
    const isPng = payload.length > 8 && payload.readUInt32BE(0) === 0x89504e47;
    out.push({
      declW: buf[o] === 0 ? 256 : buf[o],
      declH: buf[o + 1] === 0 ? 256 : buf[o + 1],
      isPng, payload,
      actual: isPng ? png(payload) : null,
    });
  }
  return out;
}

/* ---------- glyph geometry: the paths must BE the wordmark's ---------- */
const dAttrs = (svg) => [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);

function generate() {
  const src = fs.readFileSync(P('favicon-32.png'));
  const ico = buildIco(src);
  fs.writeFileSync(P('favicon.ico'), ico);
  console.log(`favicon.ico written  ${ico.length} B  sha256 ${sha(ico)}`);
  console.log(`  payload = favicon-32.png verbatim  ${src.length} B  sha256 ${sha(src)}`);
}

function check() {
  const fail = [];
  const ok = (cond, label, detail = '') => {
    (cond ? console.log : (m) => { console.log(m); fail.push(label); })(
      `  ${cond ? 'PASS' : 'FAIL'}  ${label}${detail ? '  — ' + detail : ''}`);
  };

  /* EXACT RATIFIED IDENTITY — the guard that actually pins the composition. */
  for (const [f, want] of Object.entries(RATIFIED)) {
    const got = sha(fs.readFileSync(P(f)));
    ok(got === want, `${f} is the exact ratified asset`,
       got === want ? got.slice(0, 16) + '…' : `got ${got.slice(0, 16)}… want ${want.slice(0, 16)}…`);
  }

  /* SVG */
  const svg = fs.readFileSync(P('favicon.svg'), 'utf8');
  const logo = fs.readFileSync(P('assets/logo-ASK.svg'), 'utf8');
  const fd = dAttrs(svg), ld = dAttrs(logo);
  ok(/viewBox="0 0 512 512"/.test(svg), `SVG viewBox is exactly ${VIEWBOX}`);
  ok((svg.match(new RegExp(FIELD, 'gi')) || []).length === 1, `exactly one ${FIELD} field`);
  ok(new RegExp(`<rect[^>]*fill="${FIELD}"`, 'i').test(svg), 'the field is the rect fill');
  ok(new RegExp(`fill="${INK}"`, 'i').test(svg), `wordmark fill is exactly ${INK}`);
  ok(fd.length === 3, 'exactly three wordmark paths', `found ${fd.length}`);
  ok(ld.length === 3, 'wordmark source has three paths', `found ${ld.length}`);
  ok(fd.length === 3 && ld.length === 3 && fd.every((d, i) => d === ld[i]),
     'every glyph path equals assets/logo-ASK.svg — no redraw');
  ok(!/<(filter|linearGradient|radialGradient|mask|clipPath|image|text)\b/i.test(svg),
     'no filter, gradient, mask, clip, image or text element');
  ok((svg.match(/<path\b/g) || []).length === 3, 'no extra glyph or alternate mark');

  /* rasters */
  const p32 = png(fs.readFileSync(P('favicon-32.png')));
  ok(p32.w === 32 && p32.h === 32, 'PNG fallback is exactly 32 x 32', `${p32.w}x${p32.h}`);
  const pat = png(fs.readFileSync(P('apple-touch-icon.png')));
  ok(pat.w === 180 && pat.h === 180, 'Apple touch icon is exactly 180 x 180', `${pat.w}x${pat.h}`);

  /* ICO */
  const icoBuf = fs.readFileSync(P('favicon.ico'));
  let entries = [];
  try { entries = parseIco(icoBuf); ok(true, 'ICO decodes', `${entries.length} image(s)`); }
  catch (e) { ok(false, 'ICO decodes', e.message); }
  const src32 = fs.readFileSync(P('favicon-32.png'));
  ok(entries.length > 0 && entries.every((e) => e.isPng), 'every ICO image decodes as PNG');
  ok(entries.every((e) => e.declW === e.actual.w && e.declH === e.actual.h),
     'ICO declared size matches the encoded image at every contained size');
  ok(entries.every((e) => sha(e.payload) === sha(src32)),
     'every ICO image is favicon-32.png verbatim — same composition at every size');

  /* determinism: regenerating from the same source yields identical bytes */
  const again = buildIco(src32);
  ok(sha(again) === sha(icoBuf), 'ICO generation is byte-deterministic');

  console.log('');
  console.log(`  favicon.svg           ${sha(fs.readFileSync(P('favicon.svg')))}  ${fs.statSync(P('favicon.svg')).size} B`);
  console.log(`  favicon-32.png        ${sha(src32)}  ${src32.length} B`);
  console.log(`  favicon.ico           ${sha(icoBuf)}  ${icoBuf.length} B`);
  console.log(`  apple-touch-icon.png  ${sha(fs.readFileSync(P('apple-touch-icon.png')))}  ${fs.statSync(P('apple-touch-icon.png')).size} B`);

  if (fail.length) { console.error(`\nFAILED (${fail.length}): ${fail.join(' · ')}`); process.exit(1); }
  console.log('\nbrowser-icon package: OK');
}

process.argv.includes('--check') ? check() : generate();
